# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_s <- function(h, mu, phi, sigma_eta, rho, p, m, v, a, b, Y_star, d, T) {
    .Call(`_SV_sample_s`, h, mu, phi, sigma_eta, rho, p, m, v, a, b, Y_star, d, T)
}

kalman_filter <- function(s, mu, phi, sigma_eta, rho, m, v, a, b, Y_star, d, T) {
    .Call(`_SV_kalman_filter`, s, mu, phi, sigma_eta, rho, m, v, a, b, Y_star, d, T)
}

sim_smoother <- function(s, mu, phi, sigma_eta, rho, m, v, a, b, Y_star, d, T) {
    .Call(`_SV_sim_smoother`, s, mu, phi, sigma_eta, rho, m, v, a, b, Y_star, d, T)
}

loglikelihood <- function(s, mu, phi, sigma_eta, rho, m, v, a, b, Y_star, d, mu_0, sigma_0, T) {
    .Call(`_SV_loglikelihood`, s, mu, phi, sigma_eta, rho, m, v, a, b, Y_star, d, mu_0, sigma_0, T)
}

calc_posterior_maximize <- function(x, mu, s, m, v, a, b, Y_star, d, T, mu_0, sigma_0, a_0, b_0, n_0, S_0) {
    .Call(`_SV_calc_posterior_maximize`, x, mu, s, m, v, a, b, Y_star, d, T, mu_0, sigma_0, a_0, b_0, n_0, S_0)
}

deriv1 <- function(x, mu, s, m, v, a, b, Y_star, d, T, mu_0, sigma_0, a_0, b_0, n_0, S_0) {
    .Call(`_SV_deriv1`, x, mu, s, m, v, a, b, Y_star, d, T, mu_0, sigma_0, a_0, b_0, n_0, S_0)
}

deriv2 <- function(x, mu, s, m, v, a, b, Y_star, d, T, mu_0, sigma_0, a_0, b_0, n_0, S_0) {
    .Call(`_SV_deriv2`, x, mu, s, m, v, a, b, Y_star, d, T, mu_0, sigma_0, a_0, b_0, n_0, S_0)
}

Opt <- function(x, mu, s, m, v, a, b, Y_star, d, T, mu_0, sigma_0, a_0, b_0, n_0, S_0) {
    .Call(`_SV_Opt`, x, mu, s, m, v, a, b, Y_star, d, T, mu_0, sigma_0, a_0, b_0, n_0, S_0)
}

aug_kalman_filter <- function(s, m, v, a, b, Y_star, d, T, mu, mu_0, sigma_0, a_0, b_0, n_0, S_0, call_r_opt_func) {
    .Call(`_SV_aug_kalman_filter`, s, m, v, a, b, Y_star, d, T, mu, mu_0, sigma_0, a_0, b_0, n_0, S_0, call_r_opt_func)
}

svmcmc <- function(Y, call_r_opt_func) {
    .Call(`_SV_svmcmc`, Y, call_r_opt_func)
}

